### ISSUE TITLE
Connect to IEX

### ISSUE THREAD

**Issue by vivanov879** [WojciechZankowski/iextrading4j-fix#2]
Hey, I contacted multiple brokers and they don't offer access to IEX via Fix. They only offer access to DAS for example who in turn have a FIX interface. However, instead of going through DAX, I would like to directly connect to IEX via their original Fix Api. I contacted Iex and they said brokers have the capacity to provide the direct Fix Api access. What brokers do you use?

**Comment by WojciechZankowski** [comment]
Hey, 

I was never using FIX connection to IEX. I just did the dictionary for the practice. Sorry I couldn't help 👍

**Comment by vivanov879** [comment]
Thanks for letting me know :)
